### ISSUE TITLE
Nipponsei XDCC refactoring

### ISSUE THREAD

**Issue by Chronoes** [Chronoes/auto-xdcc#1]
Refactor nipponsei-related code to support music packlists using current framework set up for episodes.

**Comment by oosran** [comment]
This issue can probably just be closed and the related code can safely be removed. It doesn't really work well with the rest of AXDCC, considering Nipponsei's releases aren't episodic in the way anime is. Also I personally don't use this at all anymore, considering there's streaming services these days that makes most of this stuff accessible anyway.

**Comment by Chronoes** [comment]
Episodic releases being different from single ones is kind of why #11 issue was done. It would be nice to get potential notifications at least for something you're interested in. Combine that with #18 and you can be more flexible with it.

Streaming services often do not have the kind of stuff like in Nipponsei so I don't think we should close it just yet.

**Comment by Chronoes** [comment]
That said, we could just remove it and add it back if needed again. It requires pretty much a complete rewrite anyway. In addition, we should clean up the main file auto_xdcc.py from old stuff.
