### ISSUE TITLE
Apostrophes in show names can cause matching problems when updating episode count

### ISSUE THREAD

**Issue by oosran** [Chronoes/auto-xdcc#32]
I think the main issue here is not actually on the plugin side of things, but rather with limitations in most common XDCC bot softwares, or something to that effect. Though it could be a good thing to handle it either way.

Short description of the problem is that a show with an apostrophe (`'`) in its name will likely be listed with the proper character in the bot's packlist, but when actually transferred it'll likely be replaced with an underscore. The problem caused by this when we add a show to the list of transfers it'll have the name from the packlist, but when the transfer finishes we try to remove the transferred file name from the list. This obviously fails because apostrophes and underscores aren't the same character, so the episode count of the show isn't updated.

As for possible solutions, there's probably plenty, but what first comes to mind is allowing a 1 or 2 character discrepancy between listed name and finished file name, possibly only for certain characters. Not sure how that would be implemented in a good way though.

**Comment by Chronoes** [comment]
Are we sure that this is caused by XDCC bot software? From what I can tell, this could be HexChat conforming to filesystem requirements. I haven't investigated fully but here is an example of DCC OFFER 
```
CR-HOLLAND|NEW has offered '[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - Director_s Cut - 01 [1080p].mkv' (3169467520 bytes)
```
I have a feeling it is HexChat related and maybe there is a way to get the original filename offered through that.

**Comment by oosran** [comment]
I can't guarantee that it's caused by XDCC bot software and not HexChat doing its own thing, but I feel like I've at some point gotten a file with an apostrophe in the filename while I've been using HexChat.

I could probably try to confirm this next time I'm at a computer by going through my list of trusted bots to see if any of them can send me something with an apostrophe in the filename.
